# Generated by Django 5.0.3 on 2024-03-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_meetup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='location',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
