# Generated by Django 5.0.3 on 2024-03-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='address',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
