# Generated by Django 5.0.3 on 2024-03-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='address',
            field=models.URLField(),
        ),
    ]
