# Generated by Django 5.0.3 on 2024-03-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_alter_meetup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
    ]
